// Auto-generated by generate-tts script
export const audioManifest = {
  "topic": "SSLExplainer",
  "voice": "vi-VN-HoaiMyNeural",
  "rate": "+10%",
  "totalScenes": 6,
  "totalDurationFrames": 1368,
  "totalDurationSec": 45.6,
  "scenes": [
    {
      "id": "scene1_hook",
      "text": "Bạn có biết SSL là gì và tại sao mỗi website đều bắt buộc phải có ổ khóa xanh trên thanh địa chỉ không?",
      "audioPath": "audio/SSLExplainer/scene1_hook.mp3",
      "filePath": "/Users/macbook/Development/remotion-cuongit-template/public/audio/SSLExplainer/scene1_hook.mp3",
      "sizeBytes": 36432,
      "estimatedDurationSec": 6.07,
      "durationInFrames": 193
    },
    {
      "id": "scene2_problem",
      "text": "Nếu không có SSL, mọi dữ liệu như mật khẩu, số thẻ ngân hàng đều bị gửi dưới dạng văn bản trần, hacker có thể đọc được ngay lập tức.",
      "audioPath": "audio/SSLExplainer/scene2_problem.mp3",
      "filePath": "/Users/macbook/Development/remotion-cuongit-template/public/audio/SSLExplainer/scene2_problem.mp3",
      "sizeBytes": 47952,
      "estimatedDurationSec": 7.99,
      "durationInFrames": 250
    },
    {
      "id": "scene3_concept1",
      "text": "SSL tạo ra một đường hầm mã hóa giữa trình duyệt và máy chủ, biến toàn bộ dữ liệu thành chuỗi ký tự không thể giải mã được.",
      "audioPath": "audio/SSLExplainer/scene3_concept1.mp3",
      "filePath": "/Users/macbook/Development/remotion-cuongit-template/public/audio/SSLExplainer/scene3_concept1.mp3",
      "sizeBytes": 42480,
      "estimatedDurationSec": 7.08,
      "durationInFrames": 223
    },
    {
      "id": "scene4_concept2",
      "text": "Quá trình bắt tay SSL gồm 3 bước: trình duyệt gửi yêu cầu, máy chủ trả về chứng chỉ số, rồi hai bên tạo khóa phiên để mã hóa.",
      "audioPath": "audio/SSLExplainer/scene4_concept2.mp3",
      "filePath": "/Users/macbook/Development/remotion-cuongit-template/public/audio/SSLExplainer/scene4_concept2.mp3",
      "sizeBytes": 47664,
      "estimatedDurationSec": 7.94,
      "durationInFrames": 249
    },
    {
      "id": "scene5_impact",
      "text": "Google ưu tiên xếp hạng website có SSL, và người dùng tin tưởng trang có ổ khóa xanh hơn gấp 3 lần so với trang không có.",
      "audioPath": "audio/SSLExplainer/scene5_impact.mp3",
      "filePath": "/Users/macbook/Development/remotion-cuongit-template/public/audio/SSLExplainer/scene5_impact.mp3",
      "sizeBytes": 43344,
      "estimatedDurationSec": 7.22,
      "durationInFrames": 227
    },
    {
      "id": "scene6_outro",
      "text": "SSL là lớp bảo vệ đầu tiên cho mọi ứng dụng web. Follow kênh để cập nhật kiến thức bảo mật mỗi ngày nhé!",
      "audioPath": "audio/SSLExplainer/scene6_outro.mp3",
      "filePath": "/Users/macbook/Development/remotion-cuongit-template/public/audio/SSLExplainer/scene6_outro.mp3",
      "sizeBytes": 43056,
      "estimatedDurationSec": 7.18,
      "durationInFrames": 226
    }
  ],
  "generatedAt": "2026-09-18T08:20:54.727Z"
} as const;
